name: Build and Deploy

# Run the deployment only when code is committed to teh branch.
on:
  push:
    branches:
      - next-release

env:
  PLUGIN_PATH: ${{ secrets.SSH_RC_PATH }}/wp-content/plugins/${{ github.event.repository.name }}/

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Get npm cache directory
      id: npm-cache
      run: echo "::set-output name=dir::$(npm config get cache)"

    - name: Configure npm cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Build
      run: npm install && grunt release-no-clean

    - name: Rsync Deployment
      uses: burnett01/rsync-deployments@4.1
      with:
        # switches: -avzr --delete
        switches: -avzr
        path: ultimate-addons-for-gutenberg/
        remote_path: ${{ env.PLUGIN_PATH }}
        remote_host: ${{ secrets.SSH_HOST }}
        remote_user: ${{ secrets.SSH_USER }}
        remote_key: ${{ secrets.SSH_KEY }}

    - name: Cleanup
      run: rm -rf ultimate-addons-for-gutenberg/
